// Generated by `src/c/moon.pkg.json` pre-build.
// This file exists only to ensure the pre-build runs when wgpu-mbt is a dependency.

#include "wgpu_stub.h"

// Keep translation unit non-empty.
int mbt_wgpu_native_prebuild_ok(void) { return 1; }
